import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const alice='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', bob='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', third='cccccccc-cccc-cccc-cccc-cccccccccccc';
let slots=[], cursor=0, effects=new Map(), user={id:alice,role:'MEMBER'}, token='token', target=bob, writes=0;
globalThis.connectionHooks={useState(initial){const i=cursor++;if(!(i in slots))slots[i]=initial;return[slots[i],v=>{writes++;slots[i]=typeof v==='function'?v(slots[i]):v;}];},useRef(initial){const i=cursor++;return slots[i]??={current:initial};},useEffect(fn,deps){const i=cursor++,old=effects.get(i);if(!old||deps.some((v,j)=>v!==old.deps[j]))effects.set(i,{fn,deps,pending:true,cleanup:old?.cleanup});}};
globalThis.connectionAuth=()=>({user,token});
globalThis.connectionRouter={useParams:()=>({id:target}),useNavigate:()=>()=>{}};
let profileRead, incomingRead, mutation, mutations=0;
globalThis.connectionApi={profile:(o,t)=>profileRead(o,t),incoming:o=>incomingRead(o),mutate:(...args)=>{mutations++;return mutation(...args);}};
globalThis.legacyApi={updateMe:async()=>({})};
const compile=file=>ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const mod=code=>import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
const load=async file=>mod(compile(file).replace(/import \{([^}]+)\} from ['"]([^'"]+)['"];?/g,(line,names,path)=>{
  if(path==='react')return `const {${names}}=globalThis.connectionHooks;`;
  if(path==='react/jsx-runtime')return line.replace(path,import.meta.resolve(path));
  if(path==='react-router-dom')return `const {${names}}=globalThis.connectionRouter;`;
  if(path.includes('authStore'))return 'const useAuthStore=globalThis.connectionAuth;';
  if(path.includes('/connections'))return 'const connectionsApi=globalThis.connectionApi;';
  if(path.includes('/api'))return 'const api=globalThis.legacyApi;';
  return names.split(',').map(n=>`const ${n.trim()}='${n.trim()}';`).join('\n');
}));
const {PublicProfile}=await load('../src/pages/PublicProfile.tsx');
const {FriendRequestsWidget}=await load('../src/shared/FriendRequestsWidget.tsx');
const nodes=t=>Array.isArray(t)?t.flatMap(nodes):t&&typeof t==='object'?[t,...nodes(t.props?.children)]:[];
const text=t=>Array.isArray(t)?t.map(text).join(''):t&&typeof t==='object'?text(t.props?.children):typeof t==='string'||typeof t==='number'?String(t):'';
let component=PublicProfile;
const render=()=>{cursor=0;return component();};
const tick=()=>new Promise(r=>setImmediate(r));
const flush=async()=>{for(const e of effects.values())if(e.pending){e.cleanup?.();e.cleanup=e.fn();e.pending=false;}await tick();};
const cleanup=()=>{for(const e of effects.values())e.cleanup?.();};
const reset=()=>{cleanup();slots=[];effects=new Map();user={id:alice,role:'MEMBER'};token='token';target=bob;};
const fixture=(owner=alice,id=bob,status='NONE')=>({version:1,ownerId:owner,targetId:id,status,contactVisible:status==='FRIEND'||status==='SELF',billingVisible:status==='SELF',profile:{id,name:'Gerçek Üye',profession:'Meslek',company:null,bio:null,profile_image:null},commonGroups:[{id:third,name:'Ortak Grup'}]});
const request=(owner=alice)=>({id:third,sender_id:bob,receiver_id:owner,status:'PENDING',sender_name:'Gerçek Gönderen',sender_profession:'Mimar'});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const click=label=>nodes(render()).find(n=>n.type==='Button'&&text(n).includes(label)).props.onClick();
profileRead=async(o,t)=>fixture(o,t);incomingRead=async()=>[];mutation=async()=>{};
assert.ok(text(render()).includes('Yükleniyor'));await flush();
assert.ok(text(render()).includes('Ortak Grup'));assert.ok(text(render()).includes('Bağlantı Kur'));
assert.ok(!text(render()).includes('Mock'));assert.ok(!text(render()).includes('İstanbul'));
const pending=deferred();mutation=()=>pending.promise;const first=click('Bağlantı Kur');click('Bağlantı Kur');assert.equal(mutations,1);
assert.equal(nodes(render()).find(n=>n.type==='Button'&&text(n).includes('Bağlantı Kur')).props.disabled,true);
profileRead=async(o,t)=>fixture(o,t,'PENDING_SENT');pending.resolve();await first;assert.ok(text(render()).includes('İstek Gönderildi'));
reset();profileRead=async()=>{throw Error('offline');};render();await flush();assert.ok(text(render()).includes('Profil yüklenemedi'));
profileRead=async(o,t)=>fixture(o,t,'PENDING_RECEIVED');click('Tekrar Dene');render();await flush();assert.ok(text(render()).includes('Kabul Et'));assert.ok(text(render()).includes('Reddet'));
mutation=async()=>{throw Error('no ACK');};await click('Kabul Et');assert.ok(text(render()).includes('Durumu yenileyip'));assert.ok(!text(render()).includes('Mesaj Gönder'));
const slow=deferred(), next=deferred();profileRead=(o,t)=>t===bob?slow.promise:next.promise;click('Durumu Yenile');render();await flush();target=third;render();await flush();const before=writes;slow.resolve(fixture());await tick();assert.equal(writes,before);assert.ok(!text(render()).includes('Gerçek Üye'));
reset();const late=deferred();profileRead=()=>late.promise;render();await flush();token='new-token';render();await flush();cleanup();const unmounted=writes;late.resolve(fixture());await tick();assert.equal(writes,unmounted);
reset();component=FriendRequestsWidget;incomingRead=async()=>[request()];render();await flush();assert.ok(text(render()).includes('Gerçek Gönderen'));assert.ok(!text(render()).includes('Bilinmeyen'));
const decision=deferred();mutation=()=>decision.promise;const count=mutations;const action=click('Kabul Et');click('Reddet');assert.equal(mutations,count+1);
incomingRead=async()=>[];decision.resolve();await action;assert.ok(text(render()).includes('Bekleyen bağlantı isteği yok'));
reset();incomingRead=async()=>{throw Error('offline');};render();await flush();assert.ok(text(render()).includes('yüklenemedi'));assert.ok(!text(render()).includes('Bekleyen bağlantı isteği yok'));
incomingRead=async()=>[request()];click('Tekrar Dene');render();await flush();const oldMutation=deferred();mutation=()=>oldMutation.promise;const oldAction=click('Reddet');user={id:third,role:'MEMBER'};incomingRead=async()=>[];assert.ok(!text(render()).includes('Gerçek Gönderen'));await flush();const changed=writes;oldMutation.resolve();await oldAction;assert.equal(writes,changed);
reset();const slowList=deferred();incomingRead=()=>slowList.promise;render();await flush();cleanup();const ended=writes;slowList.resolve([request()]);await tick();assert.equal(writes,ended);
// Actual typed service rejects foreign scope, leaked fields and unverifiable mutations.
globalThis.transport={get:async()=>fixture(),post:async()=>({success:true,ownerId:alice,targetId:bob,requestId:third,status:'PENDING_SENT',replay:false})};
const {connectionsApi}=await mod(compile('../src/api/connections.ts').replace(/import \{ referralTransport \} from ['"]\.\/api['"];?/,'const referralTransport=globalThis.transport;'));
await connectionsApi.profile(alice,bob);await connectionsApi.mutate(alice,bob,'create');
for(const bad of [null,{...fixture(),ownerId:third},{...fixture(),targetId:third},{...fixture(),status:'INVALID'},{...fixture(),profile:{...fixture().profile,email:'private'}},{...fixture(),profile:{...fixture().profile,tax_number:'private'}},{...fixture(),commonGroups:[{id:'bad',name:'x'}]}]){globalThis.transport.get=async()=>bad;await assert.rejects(connectionsApi.profile(alice,bob));}
globalThis.transport.get=async()=>[request(third)];await assert.rejects(connectionsApi.incoming(alice));
for(const bad of [{success:true},{success:true,ownerId:third,targetId:bob,requestId:third,status:'FRIEND',replay:false},{success:true,ownerId:alice,targetId:bob,requestId:third,status:'REJECTED',replay:false}]){globalThis.transport.post=async()=>bad;await assert.rejects(connectionsApi.mutate(alice,bob,'accept'));}
console.log('Connections TSX/API PASS: real profile actions and sender names, busy duplicate guard, committed refresh, failure/retry, owner/token/route/unmount stale suppression, empty versus failure, response scope/field/ACK validation. Controlled hooks; browser verified separately.');
