
CREATE TABLE IF NOT EXISTS professions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) UNIQUE NOT NULL,
  category VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO professions (name, category) VALUES
-- Hukuk & Danışmanlık
('Avukat', 'Hukuk'),
('Arabulucu', 'Hukuk'),
('Noter', 'Hukuk'),
('Fikri Haklar Danışmanı', 'Hukuk'),
('Gümrük Müşaviri', 'Hukuk & Lojistik'),
('Marka Patent Vekili', 'Danışmanlık'),
('Yönetim Danışmanı', 'Danışmanlık'),
('İK Danışmanı', 'Danışmanlık'),
('KVKK Danışmanı', 'Danışmanlık'),
('İş Geliştirme Danışmanı', 'Danışmanlık'),
('Avukat (Ticaret Hukuku)', 'Hukuk'),
('Gayrimenkul Hukuku Uzmanı', 'Hukuk'),
('Uluslararası Pazarlama Danışmanı', 'Danışmanlık'),
('İnsan Kaynakları Hizmetleri', 'Danışmanlık'),
('Kadın Girişimci Mentorluğu', 'Danışmanlık'),
('Yatırım Teşvik Danışmanı', 'Danışmanlık'),
('Gümrük Müşavirliği', 'Hukuk & Lojistik'),
('Noter ve Hukuki Müşavirlik', 'Hukuk'),
('Vize Danışmanlığı', 'Danışmanlık'),
('Hukuk Teknolojileri Çözüm Ortağı', 'Hukuk'),

-- Finans & Muhasebe & Bankacılık
('Mali Müşavir', 'Finans'),
('Yeminli Mali Müşavir', 'Finans'),
('Bağımsız Denetçi', 'Finans'),
('Banka Müdürü', 'Finans'),
('Finansal Analist', 'Finans'),
('Yatırım Danışmanı', 'Finans'),
('Sigorta Acentesi', 'Finans'),
('Bireysel Emeklilik Uzmanı', 'Finans'),
('Aktüer', 'Finans'),
('Finansal Piyasalar Analisti', 'Finans'),

-- Emlak & İnşaat & Mimarlık & Dekorasyon
('Gayrimenkul Danışmanı', 'Emlak'),
('Emlak Değerleme Uzmanı', 'Emlak'),
('Mimar', 'İnşaat'),
('İç Mimar', 'İnşaat'),
('İnşaat Mühendisi', 'İnşaat'),
('Harita Mühendisi', 'İnşaat'),
('Peyzaj Mimarı', 'İnşaat'),
('Müteahhit', 'İnşaat'),
('Yapı Denetim Uzmanı', 'İnşaat'),
('Şehir Plancısı', 'İnşaat'),
('Mimar (Konsept Tasarım)', 'İnşaat'),
('İç Mimar ve Çevre Tasarımcısı', 'İnşaat'),
('Ev Dekorasyon Ürünleri Tedarikçisi', 'İnşaat'),
('Mobilya ve Ahşap Tasarım Uygulama', 'İnşaat'),
('Anahtar Teslim Tadilat ve Dekorasyon Uzmanı', 'İnşaat'),
('Boya Badana ve Epoksi Uygulama Ustası', 'İnşaat'),
('Seramik ve Islak Zemin Uygulayıcısı', 'İnşaat'),
('Aydınlatma ve Elektrik Altyapı Çözümleri', 'İnşaat'),
('Mekanik Tesisat ve Havalandırma Sistemleri', 'İnşaat'),
('Peyzaj ve Dış Mekan Tasarımı', 'İnşaat'),
('Yapı Malzemeleri Tedarikçisi', 'İnşaat'),
('Akıllı Ev ve Bina Otomasyon Sistemleri', 'İnşaat'),

-- Teknoloji & Bilişim & Yazılım
('Yazılım Mühendisi', 'Bilişim'),
('Web Geliştirici (Frontend/Backend)', 'Bilişim'),
('Mobil Uygulama Geliştirici', 'Bilişim'),
('Veri Analisti / Veri Bilimci', 'Bilişim'),
('Siber Güvenlik Uzmanı', 'Bilişim'),
('Sistem Yöneticisi (DevOps)', 'Bilişim'),
('SEO Uzmanı', 'Bilişim'),
('E-Ticaret Yöneticisi', 'Bilişim'),
('IT Danışmanı', 'Bilişim'),
('Oyun Geliştiricisi', 'Bilişim'),
('Yazılım Geliştirici (Özel Projeler)', 'Bilişim'),
('İK Yazılımları İşletmecisi', 'Bilişim'),
('E-Ticaret Altyapı Sağlayıcısı', 'Bilişim'),
('Mobil Uygulama Geliştirme', 'Bilişim'),
('Solar Enerji Yazılımları', 'Bilişim'),
('Tarım Teknolojileri Yazılımcısı', 'Bilişim'),
('Eğitim Teknolojileri Yazılımcısı', 'Bilişim'),
('Dijital Dönüşüm Danışmanı', 'Bilişim'),
('Yapay Zeka Entegrasyon Uzmanı', 'Bilişim'),
('Dijital Kartvizit Teknolojileri', 'Bilişim'),
('Etiket ve Barkod Sistemleri', 'Bilişim'),

-- Sağlık & Medikal
('Doktor (Genel)', 'Sağlık'),
('Doktor (Diş Hekimi)', 'Sağlık'),
('Diyetisyen', 'Sağlık'),
('Psikolog', 'Sağlık'),
('Fizyoterapist', 'Sağlık'),
('Eczacı', 'Sağlık'),
('Veteriner Hekim', 'Sağlık'),
('Medikal Estetik Hekimi', 'Sağlık'),
('Optisyen', 'Sağlık'),
('Sağlık Turizmi Acentesi', 'Sağlık'),
('Klinik Psikolog', 'Sağlık'),
('Sağlık Alanı Yatırım Danışmanı', 'Sağlık'),
('Tıbbi Cihaz Satışı', 'Sağlık'),
('Diş Hastanesi İşletmecisi', 'Sağlık'),
('Estetik ve Güzellik Merkezi', 'Sağlık'),
('Sağlıklı Yaşam Danışmanlığı', 'Sağlık'),
('İlaç ve Eczacılık Hizmetleri', 'Sağlık'),
('Hemşire ve Hasta Bakım', 'Sağlık'),
('Laborant ve Radyoloji Teknikeri', 'Sağlık'),

-- Medya & İletişim & Pazarlama
('Grafik Tasarımcı', 'Medya'),
('Sosyal Medya Yöneticisi', 'Medya'),
('Dijital Pazarlama Uzmanı', 'Pazarlama'),
('Reklamcı', 'Pazarlama'),
('Halkla İlişkiler Uzmanı (PR)', 'Medya'),
('Fotoğrafçı', 'Medya'),
('Video Prodüktörü / Videographer', 'Medya'),
('Metin Yazarı', 'Medya'),
('Organizasyon / Etkinlik Yöneticisi', 'Medya'),
('Dijital Pazarlama Stratejisti', 'Pazarlama'),
('Sosyal Medya ve İçerik Yönetimi Ajansı', 'Medya'),
('Performans Pazarlaması', 'Pazarlama'),
('Dijital İletişim Ajansı Sahibi', 'Medya'),
('Marka Kalkındırma Danışmanı', 'Pazarlama'),
('Reklam Yazarı', 'Medya'),
('Medya Satın Alma Uzmanı', 'Medya'),
('Influencer Pazarlama Ajansı', 'Pazarlama'),
('Kurumsal Kimlik ve Grafik Tasarımcı', 'Medya'),
('Web Tasarım ve UI/UX', 'Medya'),
('Video Prodüksiyon Uzmanı', 'Medya'),
('Matbaa ve Ofset Baskı Merkezi', 'Medya'),
('Dijital Baskı İşletmecisi', 'Medya'),
('Promosyon Ürünleri Tasarım ve Satış', 'Pazarlama'),
('Kurumsal Hediye ve Paketleme', 'Pazarlama'),
('Ambalaj Tasarımı ve Üretimi', 'Medya'),
('Tabela ve Açık Hava Reklamcılığı', 'Medya'),
('Serigrafi ve Tekstil Baskı', 'Medya'),
('Fotoğrafçı ve Video Sanatçısı', 'Medya'),

-- Eğitim & Akademi
('Eğitim Danışmanı', 'Eğitim'),
('Kurumsal Eğitmen', 'Eğitim'),
('Dil Eğitmeni', 'Eğitim'),
('Koç (Yaşam/Kariyer)', 'Eğitim'),
('Özel Okul Kurucusu/Yöneticisi', 'Eğitim'),
('Akademisyen', 'Eğitim'),
('Teknik Eğitim Uzmanı', 'Eğitim'),
('Araştırma Görevlisi', 'Eğitim'),
('Bilim İnsanı', 'Eğitim'),
('Arkeolog ve Antropolog', 'Eğitim'),
('Sosyolog ve Felsefeci', 'Eğitim'),
('İstatistikçi ve Ekonomist', 'Eğitim'),
('Astronom ve Uzay Bilimleri', 'Eğitim'),

-- Turizm & Hizmet & Gıda
('Turizm Acentesi Sahibi', 'Turizm'),
('Otel Yöneticisi', 'Turizm'),
('Restoran Sahibi / İşletmecisi', 'Hizmet'),
('Şef / Aşçıbaşı', 'Hizmet'),
('Kafe İşletmecisi', 'Hizmet'),
('Catering Hizmetleri', 'Hizmet'),
('Güzellik Merkezi Sahibi', 'Hizmet'),
('Kuaför / Saç Tasarımcısı', 'Hizmet'),
('Spor Salonu İşletmecisi / Antrenör', 'Hizmet'),
('Siyah Sarımsak Üreticisi', 'Gıda'),
('Gurme ve Doğal Gıda Tedarikçisi', 'Gıda'),
('Organik Tarım Uygulayıcısı', 'Tarım'),
('Gıda Pazarlama ve Satış', 'Gıda'),
('Dijital Su Arıtma Cihazları', 'Hizmet'),
('Dondurulmuş Gıda Lojistiği', 'Lojistik'),
('Gıda Ambalaj Ekipmanları', 'Hizmet'),
('Turizm Acentesi', 'Turizm'),
('Kurumsal Etkinlik Planlayıcısı', 'Turizm'),
('Fuar Organizasyon', 'Hizmet'),
('Düğün Organizatörü', 'Hizmet'),
('Ses ve Işık Sistemleri', 'Hizmet'),
('Kongre Koordinatörü', 'Turizm'),

-- Lojistik & Üretim & Sanayi
('Lojistik Yöneticisi', 'Lojistik'),
('Dış Ticaret Uzmanı', 'Ticaret'),
('Fabrika Müdürü', 'Üretim'),
('Makine Mühendisi', 'Sanayi'),
('Endüstri Mühendisi', 'Sanayi'),
('Tekstil Mühendisi / Tasarımcı', 'Sanayi'),
('Gıda Mühendisi', 'Sanayi'),
('Ziraat Mühendisi', 'Tarım'),
('Makine Parçaları Üreticisi', 'Sanayi'),
('CNC Torna ve Freze İşleme', 'Sanayi'),
('Römork ve Treyler Üretimi', 'Sanayi'),
('Endüstriyel Kalıp Tasarımı', 'Sanayi'),
('Lazer Kesim ve Metal Şekillendirme', 'Sanayi'),
('Hidrolik ve Pnömatik Sistemler', 'Sanayi'),
('Yedek Parça Distribütörü', 'Sanayi'),
('Kaynak Teknolojileri', 'Sanayi'),
('Otomasyon Makinesi Üreticisi', 'Sanayi'),

-- Tekstil & Moda
('Tekstil Üreticisi', 'Tekstil'),
('Hazır Giyim Satışı', 'Tekstil'),
('Kumaş ve İplik Tedarikçisi', 'Tekstil'),
('Moda Tasarımcısı', 'Tekstil'),
('Ev Tekstili Ürünleri', 'Tekstil'),
('Ayakkabı ve Deri Mamulleri', 'Tekstil'),

-- Kamu & Yönetim
('Vali ve Kaymakamlık', 'Kamu'),
('Belediye Başkanı', 'Kamu'),
('Diplomat ve Konsolosluk', 'Kamu'),
('Müfettiş ve Denetçi', 'Kamu'),
('Emniyet Müdürü', 'Kamu'),
('Savcı ve Hakim', 'Kamu'),
('Büyükelçi', 'Kamu'),

-- Sanat & Kültür
('Sanatçı (Ressam/Müzisyen)', 'Sanat'),
('Aktör ve Tiyatro Sanatçısı', 'Sanat'),
('Yönetmen ve Senarist', 'Sanat'),
('Küratör ve Müze Yöneticisi', 'Sanat'),

-- Spor & Havacılık
('Profesyonel Sporcu', 'Spor'),
('Kaptan (Deniz/Hava)', 'Lojistik'),
('Pilot ve Kabin Memuru', 'Lojistik'),

-- Diğer
('Otomotiv Satış / Galeri', 'Otomotiv'),
('Güvenlik Sistemleri Uzmanı', 'Hizmet'),
('Baskı / Matbaa İşletmecisi', 'Hizmet')
ON CONFLICT (name) DO NOTHING;
