import {useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useAuthStore} from '../stores/authStore';
import {membershipRecordsApi,expiryRecord,type AccountRecords,type MembershipRecords as Records} from '../api/membershipRecords';
import {invoicesApi} from '../api/invoices';
import {Button} from '../shared/Button';
const value=(v:string|null)=>v===null?'Kayıt yok':v;
const date=(v:string|null)=>v?new Date(v).toLocaleString('tr-TR'):'Kayıt yok';
export function MembershipRecords({admin=false}:{admin?:boolean}){
 const actor=useAuthStore(s=>s.user),token=useAuthStore(s=>s.token),key=actor?.id+'|'+actor?.role+'|'+token+'|'+admin,navigate=useNavigate(),epoch=useRef(0);
 const [state,setState]=useState<{key:string;accounts:AccountRecords|null;detail:Records|null}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState('');
 const data=state?.key===key?state:null;
 const current=()=>{const s=useAuthStore.getState();return s.user?.id+'|'+s.user?.role+'|'+s.token+'|'+admin===key;};
 async function load(){const n=++epoch.current;setState(null);setBusy(true);setError('');try{if(!actor||admin&&actor.role!=='ADMIN')return;const accounts=admin?await membershipRecordsApi.accounts(actor.id):null,detail=admin?null:await membershipRecordsApi.read(actor.id);if(n===epoch.current&&current())setState({key,accounts,detail});}catch{if(n===epoch.current&&current())setError('Üyelik ve ödeme kayıtları yüklenemedi. Tekrar deneyin.');}finally{if(n===epoch.current&&current())setBusy(false);}}
 useEffect(()=>{setSearch('');void load();return()=>{epoch.current++;};},[key]);
 async function select(id:string){if(!data||busy||!actor||!current())return;const n=++epoch.current;setState({...data,detail:null});setBusy(true);setError('');try{const detail=await membershipRecordsApi.read(actor.id,id,true);if(n===epoch.current&&current())setState({...data,detail});}catch{if(n===epoch.current&&current())setError('Hesap kayıtları yüklenemedi. Hesabı tekrar seçin.');}finally{if(n===epoch.current&&current())setBusy(false);}}
 async function download(i:Records['invoices'][number]){if(!data?.detail||busy||!current())return;const n=epoch.current;setBusy(true);setError('');try{const blob=await invoicesApi.download('/api/invoices/'+i.id);if(n!==epoch.current||!current())return;if(blob.size!==i.size_bytes)throw Error('Invoice size differs');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=i.filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{if(n===epoch.current&&current())setError('Fatura dosyası doğrulanamadı veya indirilemedi.');}finally{if(n===epoch.current&&current())setBusy(false);}}
 if(admin&&actor?.role!=='ADMIN')return <p className="p-8">Bu ekran için yönetici yetkisi gerekir.</p>;
 const selected=data?.detail,accounts=data?.accounts?.accounts.filter(a=>[a.name,a.email].some(v=>v.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR'))))||[];
 return <main className="max-w-7xl mx-auto p-8 space-y-5"><div className="flex flex-wrap justify-between gap-3"><h1 className="text-2xl font-bold">{admin?'Üyelik ve Ödeme Kayıtları':'Üyelik ve Ödeme Kayıtlarım'}</h1><div className="flex gap-3"><Button onClick={()=>navigate(admin?'/admin/subscriptions':'/membership')}>{admin?'Üyelik Yönetimine Dön':'Üyelik Sayfasına Dön'}</Button><Button disabled={busy} onClick={()=>void load()}>Kayıtları Yenile</Button></div></div>
 <p>Hesap durumu, üyelik bitişi ve ödeme kayıtları ayrı gösterilir. Bitiş tarihinin geçmesi, hesabın kısıtlandığı veya ödemenin eksik olduğu anlamına gelmez. Bu ekran hak değiştirmez ve ödeme başlatmaz.</p>
 {busy&&<p role="status">Kayıtlar yükleniyor…</p>}{error&&<p role="alert" className="p-3 bg-red-50 text-red-800">{error}</p>}
 {data?.accounts&&<section className="space-y-3"><p>Toplam hesap: {data.accounts.accounts.length} · Hesaba bağlanmamış ödeme kaydı: {data.accounts.unownedPayments}. Bu ödemeler kanıt olmadan bir hesaba atanmaz.</p><label className="block">Hesap ara<input className="border rounded p-2 ml-3" value={search} onChange={e=>setSearch(e.target.value)} /></label><p>Gösterilen: {Math.min(100,accounts.length)} / {accounts.length}. Diğer hesapları ad veya e-posta ile arayın.</p><div className="overflow-x-auto"><table className="w-full bg-white text-sm"><thead><tr>{['Hesap','Hesap durumu','Kayıtlı plan','Bitiş zamanı','İşlem'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{accounts.slice(0,100).map(a=><tr key={a.id} className="border-t"><td className="p-3">{a.name}<p>{a.email}</p></td><td className="p-3">{value(a.account_status)}</td><td className="p-3">{value(a.subscription_plan)}</td><td className="p-3">{date(a.subscription_end_date)}<p>{expiryRecord(a,data.accounts!.asOf)}</p></td><td className="p-3"><Button disabled={busy} aria-label={'Hesap kayıtlarını göster: '+a.name} onClick={()=>void select(a.id)}>Kayıtları Göster</Button></td></tr>)}</tbody></table></div>{!accounts.length&&<p>Eşleşen hesap yok.</p>}</section>}
 {selected&&<><section className="bg-white border rounded p-5 space-y-2"><h2 className="text-xl font-bold">Kayıtlı Hesap ve Üyelik</h2><p>{selected.account.name}</p><Button onClick={()=>navigate(admin?'/admin/membership-history/'+selected.account.id:'/membership-history')}>Grup Üyelik Geçmişini Gör</Button><p>Hesap durumu: {value(selected.account.account_status)} · Plan: {value(selected.account.subscription_plan)}</p><p>Bitiş: {date(selected.account.subscription_end_date)} · {expiryRecord(selected.account,selected.asOf)}</p><p className="text-sm">Veri zamanı: {date(selected.asOf)}</p></section>
 <section className="space-y-3"><h2 className="text-xl font-bold">Hesaba Bağlı Ödeme İşlemleri</h2><p>Gösterilen: {selected.payments.length} / Toplam: {selected.totals.payments}. İşlem türü ve durumu kayıtlı değerlerdir; fatura veya üyelik hakkıyla otomatik eşleştirilmez.</p>{!selected.payments.length?<p>Hesaba bağlı ödeme kaydı yok.</p>:<div className="overflow-x-auto"><table className="w-full bg-white text-sm"><thead><tr>{['İşlem','Tür','Plan','Kayıtlı tutar','Durum','Oluşturulma'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{selected.payments.map(p=><tr key={p.id} className="border-t"><td className="p-3 break-all">{p.id}</td><td className="p-3">{value(p.action_type)}</td><td className="p-3">{value(p.plan_id)}</td><td className="p-3">{value(p.amount)}</td><td className="p-3">{value(p.status)}</td><td className="p-3">{date(p.created_at)}</td></tr>)}</tbody></table></div>}</section>
 <section className="space-y-3"><h2 className="text-xl font-bold">Hesaba Bağlı Faturalar</h2><p>Gösterilen: {selected.invoices.length} / Toplam: {selected.totals.invoices}. E-posta durumu gönderim kaydıdır; alıcının okuduğunu kanıtlamaz.</p>{!selected.invoices.length?<p>Kalıcı fatura kaydı yok.</p>:<ul className="space-y-2">{selected.invoices.map(i=><li key={i.id} className="border rounded bg-white p-3 flex flex-wrap justify-between gap-3"><span>{i.filename} · {i.size_bytes} bayt · {i.email_state} · {date(i.created_at)}</span><Button disabled={busy} onClick={()=>void download(i)} aria-label={'Faturayı indir: '+i.filename}>Faturayı İndir</Button></li>)}</ul>}</section>
 <section className="space-y-3"><h2 className="text-xl font-bold">Üyelik Hatırlatma Kayıtları</h2><p>Gösterilen: {selected.reminders.length} / Toplam: {selected.totals.reminders}. Mevcut hatırlatma işinin gönderim sonuçlarıdır.</p>{!selected.reminders.length?<p>Hatırlatma kaydı yok.</p>:<div className="overflow-x-auto"><table className="w-full bg-white text-sm"><thead><tr>{['Üyelik bitişi','Tetik günü','Gönderim kaydı','Başlangıç','Bitiş'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{selected.reminders.map(r=><tr key={r.id} className="border-t"><td className="p-3">{date(r.subscription_end_date)}</td><td className="p-3">{r.trigger_days}</td><td className="p-3">{r.delivery_state}</td><td className="p-3">{date(r.claimed_at)}</td><td className="p-3">{date(r.completed_at)}</td></tr>)}</tbody></table></div>}</section></>}
 </main>;
}
