import {groupApplicationTransport as transport} from './api';
export interface DiscoveredGroup {id:string;name:string;city:string|null;meeting_time:string|null;members:{id:string;name:string;profession:string;company:string|null;president:boolean|null}[];member_count:number;capacity:number;available_seats:number;president:string|null;president_ready:boolean;own_status:string|null;application_state:string|null}
export interface Application {id:string;group_id?:string;group_name?:string;user_id?:string;name?:string;phone?:string|null;company?:string|null;profession?:string;state:string;created_at:string;interview_at:string|null;interview_note?:string|null;decision_note?:string|null;mail_state?:string}
function owner(v:any,id:string){if(!v||v.ownerId!==id)throw Error('Başvuru yanıtının sahibi doğrulanamadı.');return v;}
const states=['AWAITING_CALL','INTERVIEWED','ACCEPTED','REJECTED'];
function applications(v:any,id:string){owner(v,id);if(!Array.isArray(v.applications)||v.applications.some((a:any)=>typeof a.id!=='string'||!states.includes(a.state)||typeof a.created_at!=='string'))throw Error('Başvuru listesi doğrulanamadı.');return v.applications as Application[];}
export const groupApplicationsApi={
 async tasks(id:string){const v=owner(await transport.get('/group-applications/tasks',id),id);if(!Array.isArray(v.tasks)||v.tasks.some((t:any)=>typeof t.id!=='string'||typeof t.group_id!=='string'||typeof t.group_name!=='string'||typeof t.applicant_name!=='string'||!['AWAITING_CALL','INTERVIEWED'].includes(t.state)))throw Error('Görüşme görevleri doğrulanamadı.');return v.tasks as {id:string;group_id:string;group_name:string;applicant_name:string;state:string}[];},
 async discover(id:string){const v=owner(await transport.get('/group-discovery',id),id);if(typeof v.hasSubscription!=='boolean'||v.geographyEnabled!==false||!Array.isArray(v.groups)||v.groups.some((g:any)=>typeof g.id!=='string'||typeof g.name!=='string'||!Array.isArray(g.members)||!Number.isInteger(g.member_count)||g.capacity!==35||!Number.isInteger(g.available_seats)||typeof g.president_ready!=='boolean'||g.members.some((m:any)=>typeof m.id!=='string'||typeof m.name!=='string'||typeof m.profession!=='string')))throw Error('Grup kataloğu doğrulanamadı.');return v as {ownerId:string;hasSubscription:boolean;groups:DiscoveredGroup[]};},
 async mine(id:string){return applications(await transport.get('/group-applications/mine',id),id);},
 async queue(id:string,group:string){const v=await transport.get(`/groups/${group}/applications`,id);if(v.groupId!==group)throw Error('Grup bağlamı doğrulanamadı.');return applications(v,id);},
 async join(id:string,group:string){const v=owner(await transport.post(`/groups/${group}/join`,{},id),id);if(!v.alreadyMember&&(!v.application||typeof v.application.id!=='string'||!states.includes(v.application.state)))throw Error('Başvuru kaydı doğrulanamadı.');return v;},
 async act(id:string,application:string,action:string,body:unknown){const v=owner(await transport.post(`/group-applications/${application}/${action}`,body,id),id);if(v.application?.id!==application||!states.includes(v.application.state))throw Error('Başvuru işlemi doğrulanamadı. Listeyi yenileyin.');return v;},
};
export function applicationError(e:any){try{const v=JSON.parse(e.responseBody);if(typeof v.error==='string')return v.error;}catch{}return 'İşlem doğrulanamadı. Listeyi yenileyerek durumu kontrol edin.';}
export const applicationLabel=(s:string)=>({AWAITING_CALL:'Telefon görüşmesi bekleniyor',INTERVIEWED:'Görüşme yapıldı, karar bekleniyor',ACCEPTED:'Kabul edildi',REJECTED:'Reddedildi'}[s]??s);
