import {referralTransport} from './api';
export interface MembershipState {group_id:string;group_name:string|null;role:string|null;status:string|null;joined_at:string|null}
export interface MembershipEvent {id:string;user_id:string;user_name:string|null;operation:'BASELINE'|'INSERT'|'UPDATE'|'DELETE';recorded_at:string;before_state:MembershipState|null;after_state:MembershipState|null}
export interface HistoryPage {version:1;ownerId:string;targetId:string;asOf:string;total:number;events:MembershipEvent[];next:{beforeAt:string;beforeId:string}|null}
const uuid=(v:any)=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(v);
const nullable=(v:any)=>v===null||typeof v==='string';
const date=(v:any)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const state=(s:any)=>s===null||!!s&&uuid(s.group_id)&&nullable(s.group_name)&&nullable(s.role)&&nullable(s.status)&&(s.joined_at===null||date(s.joined_at));
export function validHistory(d:any,owner:string,target:string):d is HistoryPage {return !!d&&d.version===1&&uuid(owner)&&uuid(target)&&d.ownerId===owner&&d.targetId===target&&date(d.asOf)&&Number.isSafeInteger(d.total)&&d.total>=0&&Array.isArray(d.events)&&d.events.length<=50&&d.events.length<=d.total&&d.events.every((e:any)=>!!e&&uuid(e.id)&&e.user_id===target&&nullable(e.user_name)&&['BASELINE','INSERT','UPDATE','DELETE'].includes(e.operation)&&date(e.recorded_at)&&state(e.before_state)&&state(e.after_state)&&(e.before_state!==null||e.after_state!==null))&&new Set(d.events.map((e:any)=>e.id)).size===d.events.length&&(d.next===null||!!d.next&&d.events.length===50&&d.next.beforeAt===d.events.at(-1).recorded_at&&d.next.beforeId===d.events.at(-1).id);}
export const membershipHistoryApi={async read(owner:string,target=owner,admin=false,cursor:HistoryPage['next']=null){if(!uuid(owner)||!uuid(target)||!admin&&target!==owner)throw Error('Invalid history owner');const query=cursor?'?'+new URLSearchParams(cursor).toString():'';const d=await referralTransport.get((admin?'/admin/membership-history/'+target:'/membership-history')+query);if(!validHistory(d,owner,target))throw Error('Invalid history response');return d;}};
